#ifndef RESOURCE_H
#define RESOURCE_H

#define		IDI_FOLDER_ICON	101
#define		IDI_TEXT_ICON	102
#define		IDI_PNG_ICON	103
#define		IDI_JPG_ICON	104
#define		IDI_ZIP_ICON	105
#define		IDI_FILE_ICON	106
#define		IDI_AUDIO_ICON	107
#define		IDI_SHADER_ICON 108

#endif // !RESOURCE_H
